packageExtensions:
  "@fastify/autoload@*":
    peerDependencies:
      fastify: "^5"
  "@fastify/cors@*":
    peerDependencies:
      fastify: "^5"
  "fastify-plugin@*":
    peerDependencies:
      fastify: "^5"